### PR TITLE
Update Files.txt

### PR DESCRIPTION
**Pull request by IceKickr**
Updated with info on starting ysbox.exe and ysgen.exe directly, without going through yserbius.exe

### CODE REVIEW

**Comment by ZaneDubya** [comment]
@pchernik I clarified how to use the parameters you indicated. Interesting find! -ZW

**Comment by IceKickr** [comment]
Have you figured out what the medallions do? Netherworld, etc?

**Comment by ZaneDubya** [comment]
Yes - they don't do much.

Data is here: https://github.com/ZaneDubya/YserbiusData/blob/master/Yserbius/Data/Items.csv

The MonGroup and MonEffect fields from that data are the only thing that I think could encode some kind of effect. Those fields are loaded into memory, but as far as I can tell, those fields are never referenced by the original game's map script or combat handlers.

This is also the case for some of the monster data - that data also has fields that are loaded into memory but never referenced.

**Comment by ZaneDubya** [comment]
If I were to hazard a guess, I would say that those items were intended to increase the damage done to monsters of the type encoded in MonGroup, or to reduce the damage taken from those monsters, or both. But as I wrote, the data is not actually used by the original game.

**Comment by IceKickr** [comment]
What do the item flags do? 64 / 96 / 32 / 192

[image: image.png]

**Comment by ZaneDubya** [comment]
It is a bitfield indicating if the item causes the player to resists debuff states: poison, petrify, etc.

**Comment by IceKickr** [comment]
Oh! So wouldn't that explain the medallions then, as each one resisting a
different state?

**Comment by ZaneDubya** [comment]
Ah, excellent point! Yes, it would!

The tooltips in the game should reflect that correctly. I haven't looked at the item data fields in over a year, so I admit I'm a little rusty in my recall. :)

**Comment by IceKickr** [comment]
Haha... Gotcha. Thanks for the info.

**Pull request merged**
